### ISSUE TITLE
Provide more refined configuration of Devops agent

### ISSUE THREAD

**Issue by JohnNiang** [LinuxSuRen/ks-devops#19]
Also look at <https://github.com/kubesphere/ks-installer/pull/1544>.

However, I will implement this feature in controller manager instead of in ks-installer. 

BTW, Any implementation design will be updated here.

**Comment by JohnNiang** [comment]
### 关于 Jenkins agent resource limit 配置

此前，Jenkins agent resource limit 配置是在 clusterconfiguration ks-installer 配置下，请参考：<https://github.com/kubesphere/ks-installer/pull/1544>。

现在，ks-devops 已经从 kubesphere 中抽离，理论上关于 devops 的逻辑都应该在新项目中，而不应该在 kubesphere 中，更不应该在 ks-installer 中。

两种实施方案：

1. 原方案（暂不考虑）
2. 自定义 CRD，如 devopsconfiguration：jenkins。

   - 监听 jenkins 配置的变化，作出对应的修改。
   - 优点：不会对已有的配置造成任何影响
   - 缺点：需要增加额外的配置

3. 在 configmap：devops 中添加该配置

   - 同样是监听 configmap 变化，作出对应的修改。
   - 优点：方便快捷
   - 缺点：ks-devops 更新操作可能会覆盖掉修改的 configmap

**Comment by JohnNiang** [comment]
关于方案 2 的补充：

CRD 对应的 CR 的形态设计：

```yaml
apiVersion: config.devops.kubesphere.io/v1
kind: DevOpsConfig
jenkins:
    agent:
        resourceLimit: default | high | custom
... // other configuration
```

**Comment by LinuxSuRen** [comment]
我倾向于方案3，对于“ks-devops 更新操作可能会覆盖掉修改的 configmap“，具体是为什么呢？个人以为不会发生这种情况。另外，在 ConfigMap 中不建议把 value 设置为一个 `xxx.yaml`，直接在 ConfigMap 中添加 `key-value` 即可。

**Comment by JohnNiang** [comment]
关于方案 3 的补充：

配置的最终形态如下：

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    
```

**Comment by JohnNiang** [comment]
> 我倾向于方案3，对于“ks-devops 更新操作可能会覆盖掉修改的 configmap“，具体是为什么呢？个人以为不会发生这种情况。另外，在 ConfigMap 中不建议把 value 设置为一个 `xxx.yaml`，直接在 ConfigMap 中添加 `key-value` 即可。

由于 ConfigMap 天生和方案 2 的设计吻合，最终采用方案 3。

> 之前我误以为需要在 devops configmap 中添加配置，所以才会提到更新 ks-devops 至新版的时候可能会被我们的默认配置覆盖掉。

**Comment by JohnNiang** [comment]
### 实施思路：

1. 提供两种预定义场景：默认配置和高配置  + 一种自定义场景：自定义配置。
其中与定义场景由我们自己提供，建议放入 helm charts 中。而自定义配置则留给用户在后期自行配置。

2. 配合 jenkins.agent.pod_resource_limit 配置进行相应的应用。

### 好处：

用户不直接修改任何预定义配置，而是增加一个自定义配置即可。

### 例子：jenkins-casc-config configmap 的自定义

用户可直接新增 jenkins-casc-config_custom configmap，并配置需要自定义的部分即可。

jenkins-casc-config configmap 部分配置:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-config
data:
  jenkins.yaml: |
    jenkins:
      mode: EXCLUSIVE
      numExecutors: 5
      scmCheckoutRetryCount: 2

      clouds:
        - kubernetes:

...
```

jenkins-casc-config-custom configmap 可这样配置：

```diff
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-config
data:
  jenkins.yaml: |
    jenkins:
-     numExecutors: 5
+     numExecutors: 100000000
```
